apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-two
  labels:
    app: web-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-two
  template:
    metadata:
      labels:
        app: web-two
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80